### ISSUE TITLE
mongorestore is missing in the 1.0.0-rc2

### ISSUE THREAD

**Issue by colonia27** [Sing-Li/Rocket.Chat.Embedded.armhf#6]
looks like mongorestore is missing in the 1.0.0-rc2. I can only see mongoimport and mongoexport.

`cat /var/snap/rocketchat-server/common/restore/mongorestore.log
/snap/rocketchat-server/1370/bin/restoredb: line 62: mongorestore: command not found`

in case "mongoimport" is the former "mongorestore" this needs to be changed in the restoredb script.

**Comment by Sing-Li** [comment]
Thanks!  Verified and should be fixed shortly.
